name: intellij-eta
version: '0.0.1-SNAPSHOT'
license: AllRightsReserved
default-extensions:
- DataKinds
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MagicHash
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeFamilies
- TypeOperators
- UnboxedTuples
library:
  source-dirs: src/main/eta
  dependencies:
  - base >=4.8 && <4.9
tests:
  test:
    main: Main.hs
    source-dirs: src/test/eta
    dependencies:
    - base
    - intellij-eta
