name: intellij-eta
version: '0.0.1-SNAPSHOT'
license: AllRightsReserved

default-extensions:
- DataKinds
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MagicHash
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeFamilies
- TypeOperators
- UnboxedTuples

dependencies:
- base >=4.8 && <4.9
- eta-parser

library:
  source-dirs: src/main/eta

tests:
  test:
    main: Main.hs
    source-dirs: src/test/eta
    dependencies:
    - intellij-eta
